### PR TITLE
Exchanged the extensions for the favor of pluggable interface-based providers

### PR DESCRIPTION
**Pull request by weitzhandler**
See #12.

### CODE REVIEW

**Comment by tonysneed** [comment]
Thanks for this ... I plan to have a look over the weekend.

**Comment by weitzhandler** [comment]
Any news?

**Comment by tonysneed** [comment]
Just coming off an insane work period. Let’s connect on Sunday via Skype if you’re avail.  Great idea to design things to be extensible. :)

**Comment by weitzhandler** [comment]
Are you still working on this repo?

**Comment by tonysneed** [comment]
I've been waiting until EF 2.1 reached RC and the API stabilizes, so I can update the packages.

Would like to schedule a planning session with @lelong37 on refactoring for extensibility.

**Comment by weitzhandler** [comment]
Ah. I see.
BTW, here's some interesting [feature](https://docs.microsoft.com/en-us/ef/core/modeling/constructors#injecting-services).

**Comment by tonysneed** [comment]
@lelong37 Can we get together sometime this week to look at this?

**Comment by tonysneed** [comment]
Sorry this PR got pushed to the back burner for a while.  :(   I looked at the extensibility points you wanted to introduce and, from an architectural perspective, you are proposing to implement a [strategy pattern](https://en.wikipedia.org/wiki/Strategy_pattern) by adding interface parameters to specific extension methods. This approach does make some sense, given the use of extension methods for the API.  However, the refactoring feels a bit like it violates the [YAGNI](https://martinfowler.com/bliki/Yagni.html) principle.  Before adding strategies I would want to have specific use cases where it would make sense to allow the caller to supply a strategy, and it would probably be narrower in scope.  For example, a possible strategy candidate might be for the `SetEntityState` method, which could be replaced with a delegate (which is more flexible than an interface).  But again I would want to see a concrete use case before undertaking a re-engineering of the architecture.

**Comment by tonysneed** [comment]
Will re-open if needed.

**Comment by weitzhandler** [comment]
It's based on IoC DI of .NET Framework. ASP.NET Core and EF Core are massively using this pattern, so really it doesn't matter what container you're using, whatever 'service' you're overriding and re-registering will work.  
I'm not using TE at the moment, and can't currently mess around with the code here.
Best wishes Tony.

**Comment by tonysneed** [comment]
@weitzhandler Thanks for your input and prior interest. I don't find many people currently using TE, so I will need to triage things. All the best to you too!

**Pull request closed without merging**
