### PR TITLE
Update to .NET6

### PR DESCRIPTION
**Pull request by samantha-letourneau**
Update packages to .NET6

### CODE REVIEW

**Comment by tonysneed** [comment]
@samantha-letourneau Thanks, very nice of you to submit this PR. I will make a few adjustments and merge.

Issue #46 seems to indicate that a code change may also be required.

**Comment by samantha-letourneau** [comment]
@tonysneed I'm glad you accept this PR :) When it will be merged, I'll also add a PR for https://github.com/urfnet/URF.Core  :)

**Comment by tonysneed** [comment]
Included in release https://github.com/TrackableEntities/TrackableEntities.Core/releases/tag/v6.0.0

**Comment by tonysneed** [comment]
> When it will be merged, I'll also add a PR for https://github.com/urfnet/URF.Core :)

Thanks for letting me know about this. I took care of it: https://github.com/urfnet/URF.Core/releases/tag/v6.0.0

Cheers!

**Pull request merged**
