### PR TITLE
Support EF Core 8

### PR DESCRIPTION
**Pull request by Jaben**
PR for Issue #50

### CODE REVIEW

**Comment by tonysneed** [comment]
Thanks @Jaben! I'll test and merge this.

**Comment by Jaben** [comment]
> Thanks @Jaben! I'll test and merge this.

We're all busy folks, I know -- but, is there any chance of pulling this down this week and taking a look? I'd like to get it merged so I can update our targets to EF 8.

FYI I did run tests on the new EF 8 targets and everything is good:

image

**Comment by Jaben** [comment]
@tonysneed I could help maintain this project if it's become a burden for you. I like doing project maintenance as it tends to be bite-sized tasks (usually a few hours at most) and rather rewarding since you (often) get to release a new library version when you're done.

**Comment by tonysneed** [comment]
Yes, I would very much appreciate it! Can you connect with tonysneed on LinkedIn? I could enable you to merge your PR.

**Comment by Jaben** [comment]
> Yes, I would very much appreciate it! Can you connect with tonysneed on LinkedIn? I could enable you to merge your PR.

Absolutely -- done.

**Comment by dphoebus** [comment]
+1 for promoting this merge!

**Pull request merged**
